### PR TITLE
CleanupNeos 9.0 composer.json

### PR DESCRIPTION
**Pull request by mhsdesign**
Fixes: https://github.com/neos/neos-development-collection/issues/5215

### CODE REVIEW

**Review by kitsunet — CHANGES_REQUESTED** [review]
IMHO won't work, this mostly needs to be fixed in https://github.com/neos/neos-development-distribution/blob/9.0/Build/set-dependencies.sh
AND you need to take the stability flag into account as for non stable releases we want/should/need to require the respective dev/beta versions specifically here. So e.g. neos/media etc should stay. I think set-dependencies needs to be adapted to set the dependency on the dbaladapter.

**Comment by mhsdesign** [comment]
> AND you need to take the stability flag into account as for non stable releases we want/should/need to require the respective dev/beta versions specifically here. So e.g. neos/media etc should stay.

Fair enough but i that should not be necessary as `neos/fusion-afx` `neos/timeable-node-visibility` `neos/contentrepository-core` etc are not required manually here as well but are installed never the less due to the dependency set in `neos/neos`. @nezaniel  and me figured  that it would just be useless and wrong to manually require `neos/fusion` here ...

**Comment by kitsunet** [comment]
It works due to our/my own quickhack / fix here: https://github.com/neos/neos-base-distribution/commit/39f7d21bc2c26d6e461a566468aee1cbd4a0cdc1 
With minimum-stability. But I would probably not want to leave it at that once we have a stable version (TBD), true though we could decide for either or. Actually that would maybe be the right choice? We throw all these dependencies out here, and the set-dependencies script in "STABILITY_FLAG" mode instead just sets the minimum-stability/prefer-stable things, because that should be enough 🤔

**Review by kitsunet — APPROVED** [review]
I think I like the idea I mentioned in the comment before, so no block anymore, as then this change would be good. That change to set-depdenncies needs to happen before next beta though, otherwise we will just get all these dependencies back in here.

**Comment by mhsdesign** [comment]
see https://github.com/neos/neos-development-distribution/commit/a0fb7ce53c0bb734aa59190a4a014b383b00f3ca

**Pull request merged**
