### PR TITLE
TASK: Require symfony/css-selector needed for Neos functional tests

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
This has been added to the development distribution with neos/neos-development-distribution@f689c7a3820ec19a85beea4476abfd529941484e but never to the base distribution.

**Comment by kdambekalns** [comment]
@aertmann @robertlemke

**Comment by aertmann** [comment]
hmm guess it should go into 2.0 or 1.2 then? that's how it is in the development dist..

**Comment by kdambekalns** [comment]
Rly? Ok, I assumed 2.1, because of the date is was committed/merged there. I'd say it's nice to have, but not strictly needed, since most people will probably not run the Neos tests themselves on the base dist. Feel free to move this to another branch… or wait a bit. :)

**Comment by aertmann** [comment]
@kdambekalns that was the reason it wasn't added in the first place, but I can see the argument that it makes sense all the tests of the base dist can be run after installing..

**Comment by kdambekalns** [comment]
Another option: do it like with pdo-sqlite, `suggest` it in the manifest.

**Comment by kdambekalns** [comment]
Replaced by https://github.com/neos/neos-base-distribution/pull/14 against the 1.2 branch

**Pull request closed without merging**
