### PR TITLE
FEATURE: Add dependency to Neos.Fusion.Form

### PR DESCRIPTION
**Pull request by mficzel**

### CODE REVIEW

**Comment by mficzel** [comment]
This finalizes the release of fusion form 1.0.0 https://github.com/neos/fusion-form/issues/29

**Review by albe — APPROVED** [review]

**Comment by bwaidelich** [comment]
As I'm slightly in favor of slim distributions: Is `Neos.Fusion.Form` really required by the base distribution or what are the thoughts behind this new dependency?

**Comment by mficzel** [comment]
@bwaidelich it will become a dependency of Neos itself as soon as we start writing be modules in fusion. 

The dependency here is mainly to make it already part of the default distribution and announce it with the 5.1 Neos release.

**Comment by mficzel** [comment]
Also the plan is to incorporate fusion forms into the dev distribution once we consider it mature enough to follow the Neos major release rhythm.

**Pull request merged**
