### PR TITLE
BUGFIX: Add missing dependency to Neos.Diff

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Another one for @aertmann and @kitsunet - the dev distribution doesn't need it.

**Comment by kdambekalns** [comment]
:+1: - works for me

**Comment by aertmann** [comment]
needs to go into https://github.com/neos/neos-development-distribution as well

**Comment by kdambekalns** [comment]
@aertmann Why? It's part of the development collection, thus doesn't need to be "whitelisted" for stability. We do not list any of the other packages in the development collection in the dev-dist composer manifest, either.

**Comment by aertmann** [comment]
@kdambekalns ah right, mixed it up with the non collection packages https://github.com/neos/neos-development-distribution/blob/master/composer.json.. nvm

**Pull request merged**
